import HeadingDashboard from "../components/Heading/HeadingDashboard";
import Navbar from "../components/Navbar/Navbar";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PerpustakaanKu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " bg-slate-100 text-slate-950 dark:bg-slate-900 dark:text-slate-200 transition-colors"
        }
      >
        <Navbar />
        <main className="px-4 md:px-0 mx-auto container">
          <HeadingDashboard />
          {children}
        </main>
      </body>
    </html>
  );
}
